### ISSUE TITLE
NoClassDefFoundError: dev/wolveringer/configuration/Configuration

### ISSUE THREAD

**Issue by JonathanVil** [WolverinDEV/BungeeUtil#15]
Getting this error when loading 2.0.1:

`16:34:10 [WARNING] Exception encountered when loading plugin: BungeeUtil
java.lang.NoClassDefFoundError: dev/wolveringer/configuration/Configuration
	at dev.wolveringer.bungeeutil.plugin.Main.onEnable(Main.java:50)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:272)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: dev.wolveringer.configuration.Configuration
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more`

**Comment by JonathanVil** [comment]
Used wrong jar - Should use standalone. Closing.
