### ISSUE TITLE
Packet Error

### ISSUE THREAD

**Issue by JonathanVil** [WolverinDEV/BungeeUtil#16]
Getting this error every second:
```
16:39:09 [SEVERE] io.netty.handler.codec.DecoderException: Packet error (Version: v1_11_0, Readed version: v1_11, Class: dev.wolveringer.bungeeutil.packets.PacketPlayOutScoreboardTeam, Id: 0x41) -> The received string length is longer than maximum allowed (19 > 16)
16:39:09 [SEVERE] 	at dev.wolveringer.bungeeutil.packetlib.reader.PacketDataSerializer_v1_8.c(PacketDataSerializer_v1_8.java:188)
16:39:09 [SEVERE] 	at dev.wolveringer.bungeeutil.packetlib.reader.PacketDataSerializer_v1_8.readString(PacketDataSerializer_v1_8.java:231)
16:39:09 [SEVERE] 	at dev.wolveringer.bungeeutil.packets.PacketPlayOutScoreboardTeam.read(PacketPlayOutScoreboardTeam.java:120)
16:39:09 [SEVERE] 	at dev.wolveringer.bungeeutil.packets.Packet.load(Packet.java:254)
16:39:09 [SEVERE] 	at dev.wolveringer.bungeeutil.packets.NormalPacketCreator.getPacket0(NormalPacketCreator.java:100)
16:39:09 [SEVERE] 	at dev.wolveringer.bungeeutil.packets.AbstractPacketCreator.getPacket(AbstractPacketCreator.java:58)
16:39:09 [SEVERE] 	at dev.wolveringer.bungeeutil.packets.Packet.getPacket(Packet.java:152)
16:39:09 [SEVERE] 	at dev.wolveringer.bungeeutil.netty.WarpedMinecraftDecoder.decode(WarpedMinecraftDecoder.java:117)
16:39:09 [SEVERE] 	at dev.wolveringer.bungeeutil.netty.WarpedMinecraftDecoder.decode(WarpedMinecraftDecoder.java:29)
16:39:09 [SEVERE] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
16:39:09 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
16:39:09 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
16:39:09 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
16:39:09 [SEVERE] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
16:39:09 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
16:39:09 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
16:39:09 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
16:39:09 [SEVERE] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
16:39:09 [SEVERE] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
16:39:09 [SEVERE] 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
16:39:09 [SEVERE] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
16:39:09 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
16:39:09 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
16:39:09 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
16:39:09 [SEVERE] 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
16:39:09 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
16:39:09 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
16:39:09 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
16:39:09 [SEVERE] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
16:39:09 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
16:39:09 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
16:39:09 [SEVERE] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
16:39:09 [SEVERE] 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1018)
16:39:09 [SEVERE] 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:402)
16:39:09 [SEVERE] 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:307)
16:39:09 [SEVERE] 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
16:39:09 [SEVERE] 	at java.lang.Thread.run(Thread.java:745)
```

- I use 2.0.1
- This also happens when using 1.10, 1.8.9, etc.

**Comment by WolverinDEV** [comment]
Hmm okey.
Did you tested it with no plugins?
 I know that sometimes a costume scoreboard plugin
 ignores the maximum length of 16 for team prefix and suffix.

PS: I changed the format of the error. You used \` you have to use it 3 times like this: \`\`\` :D

**Comment by JonathanVil** [comment]
Thanks!
My scoreboard plugin was the problem.
