### ISSUE TITLE
Error when loading

### ISSUE THREAD

**Issue by EvertonMJr** [WolverinDEV/BungeeUtil#22]
**Error:**
```
02:01:03 [WARNING] Exception encountered when loading plugin: BungeeUtil
java.lang.NoClassDefFoundError: dev/wolveringer/configuration/Configuration
    at dev.wolveringer.bungeeutil.plugin.Main.onEnable(Main.java:49)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:272)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: dev.wolveringer.configuration.Configuration
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 5 more
```
**BungeeUtil Version:** 2.1.2

**BungeeCord Version:** Build #1222

**When it happened:** When I started Bungeecord, while loading.

**Computer system and architecture:** Windows 10, 64 bits

**_Thank you! I hope you can solve this. This plugin is the most amazing one I've ever seen._**

**Comment by WolverinDEV** [comment]
Hey are you using the standalone version?

**Comment by EvertonMJr** [comment]
Sorry, the standalone version would be...?

**Comment by EvertonMJr** [comment]
Oh, I'm sorry. I didn't know that I needed to use the standalone version in order for it to work. Now I used it and everything is running fine. Sorry!

**Comment by WolverinDEV** [comment]
No problem my friend.

Well of you only usses the "normal" version than you havnt included the dependencies and you have to install it by your own. (The missiong dependency courses also the class not found error)

At the standalone version all this dependencies are alredy included (via maven-shade)

**Comment by EvertonMJr** [comment]
Oh, thanks! I didn't know what the standalone version was at all. Thank you for the help!
