### ISSUE TITLE
NullPointerException at WarpedMinecraftDecoder

### ISSUE THREAD

**Issue by Janmm14** [WolverinDEV/BungeeUtil#25]
```
12:32:44 [SCHWERWIEGEND] java.lang.NullPointerException
12:32:44 [SCHWERWIEGEND] 	at dev.wolveringer.bungeeutil.netty.WarpedMinecraftDecoder.setProtocolVersion(WarpedMinecraftDecoder.java:92)
12:32:44 [SCHWERWIEGEND] 	at dev.wolveringer.bungeeutil.netty.WarpedChannelWrapper.setVersion(WarpedChannelWrapper.java:70)
12:32:44 [SCHWERWIEGEND] 	at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:263)
12:32:44 [SCHWERWIEGEND] 	at net.md_5.bungee.protocol.packet.Handshake.handle(Handshake.java:44)
12:32:44 [SCHWERWIEGEND] 	at dev.wolveringer.bungeeutil.netty.WarpedChannelHandler.channelRead(WarpedChannelHandler.java:91)
12:32:44 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
12:32:44 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
12:32:44 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
12:32:44 [SCHWERWIEGEND] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
12:32:44 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
12:32:44 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
12:32:44 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
12:32:44 [SCHWERWIEGEND] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
12:32:44 [SCHWERWIEGEND] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
12:32:44 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
12:32:44 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
12:32:44 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
12:32:44 [SCHWERWIEGEND] 	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:219)
12:32:44 [SCHWERWIEGEND] 	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:631)
12:32:44 [SCHWERWIEGEND] 	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:468)
12:32:44 [SCHWERWIEGEND] 	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:428)
12:32:44 [SCHWERWIEGEND] 	at net.md_5.bungee.protocol.LegacyDecoder.decode(LegacyDecoder.java:37)
12:32:44 [SCHWERWIEGEND] 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
12:32:44 [SCHWERWIEGEND] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
12:32:44 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
12:32:44 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
12:32:44 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
12:32:44 [SCHWERWIEGEND] 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
12:32:44 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
12:32:44 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
12:32:44 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
12:32:44 [SCHWERWIEGEND] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
12:32:44 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
12:32:44 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
12:32:44 [SCHWERWIEGEND] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
12:32:44 [SCHWERWIEGEND] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
12:32:44 [SCHWERWIEGEND] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651)
12:32:44 [SCHWERWIEGEND] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574)
12:32:44 [SCHWERWIEGEND] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488)
12:32:44 [SCHWERWIEGEND] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)
12:32:44 [SCHWERWIEGEND] 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
12:32:44 [SCHWERWIEGEND] 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by WolverinDEV** [comment]
When douse this error course?

**Comment by WolverinDEV** [comment]
```
dev.wolveringer.bungeeutil.netty.WarpedMinecraftDecoder.setProtocolVersion(WarpedMinecraftDecoder.java:92)
```
-> https://github.com/WolverinDEV/BungeeUtil/blob/2.0/src/main/java/dev/wolveringer/bungeeutil/netty/WarpedMinecraftDecoder.java#L92
Line 92 isnt the methode WarpedMinecraftDecoder#setProtocolVersion

**Comment by Janmm14** [comment]
oh, I thought I updated to latest but apparantly not
