### ISSUE TITLE
Multiple NPE's due to usage of unsafe class initialization inside the PacketHolder

### ISSUE THREAD

**Issue by Janmm14** [WolverinDEV/BungeeUtil#30]
Compiled 2.3.0 from source, re-checked with decompiler, debug output says
`this.properties = null`
Made field final, removed `@...Constructor` from main class, didn't help.
```02:32:24 [INFORMATION] An error happed. .NullPointerException message -> Packet error (Version: v1_8_0, Class: null, Id: 0x20) -> null
02:32:24 [SCHWERWIEGEND] java.lang.NullPointerException: Packet error (Version: v1_8_0, Class: null, Id: 0x20) -> null
02:32:24 [SCHWERWIEGEND]        at dev.wolveringer.bungeeutil.packets.PacketPlayOutEntityProperties.read(PacketPlayOutEntityProperties.java:70)
02:32:24 [SCHWERWIEGEND]        at dev.wolveringer.bungeeutil.packets.Packet.load(Packet.java:301)
02:32:24 [SCHWERWIEGEND]        at dev.wolveringer.bungeeutil.packets.creator.NormalPacketCreator.getPacket0(NormalPacketCreator.java:84)
02:32:24 [SCHWERWIEGEND]        at dev.wolveringer.bungeeutil.packets.creator.NormalPacketCreator.getPacket0(NormalPacketCreator.java:96)
02:32:24 [SCHWERWIEGEND]        at dev.wolveringer.bungeeutil.packets.creator.CachedPacketCreator.getPacket0(CachedPacketCreator.java:132)
02:32:24 [SCHWERWIEGEND]        at dev.wolveringer.bungeeutil.packets.creator.AbstractPacketCreator.getPacket(AbstractPacketCreator.java:49)
02:32:24 [SCHWERWIEGEND]        at dev.wolveringer.bungeeutil.packets.Packet.getPacket(Packet.java:158)
02:32:24 [SCHWERWIEGEND]        at dev.wolveringer.bungeeutil.netty.WarpedMinecraftDecoder.decode(WarpedMinecraftDecoder.java:97)
02:32:24 [SCHWERWIEGEND]        at dev.wolveringer.bungeeutil.netty.WarpedMinecraftDecoder.decode(WarpedMinecraftDecoder.java:31)
02:32:24 [SCHWERWIEGEND]        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
02:32:24 [SCHWERWIEGEND]        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
02:32:24 [SCHWERWIEGEND]        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
02:32:24 [SCHWERWIEGEND]        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
02:32:24 [SCHWERWIEGEND]        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
02:32:24 [SCHWERWIEGEND]        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
02:32:24 [SCHWERWIEGEND]        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
02:32:24 [SCHWERWIEGEND]        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
02:32:24 [SCHWERWIEGEND]        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
02:32:24 [SCHWERWIEGEND]        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
02:32:24 [SCHWERWIEGEND]        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
02:32:24 [SCHWERWIEGEND]        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
02:32:24 [SCHWERWIEGEND]        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
02:32:24 [SCHWERWIEGEND]        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
02:32:24 [SCHWERWIEGEND]        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
02:32:24 [SCHWERWIEGEND]        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
02:32:24 [SCHWERWIEGEND]        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
02:32:24 [SCHWERWIEGEND]        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
02:32:24 [SCHWERWIEGEND]        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
02:32:24 [SCHWERWIEGEND]        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
02:32:24 [SCHWERWIEGEND]        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
02:32:24 [SCHWERWIEGEND]        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
02:32:24 [SCHWERWIEGEND]        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651)
02:32:24 [SCHWERWIEGEND]        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574)
02:32:24 [SCHWERWIEGEND]        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488)
02:32:24 [SCHWERWIEGEND]        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)
02:32:24 [SCHWERWIEGEND]        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
02:32:24 [SCHWERWIEGEND]        at java.lang.Thread.run(Thread.java:745)
```

Changing ExceptionUtils to just create a new runtime exception and with debug output on the error still occurrs:

```
02:57:39 [INFORMATION] this.properties = null
02:57:39 [INFORMATION] An error happed. .RuntimeException message -> Packet error (Version: v1_8_0, Class: null, Id: 0x20) -> null
02:57:39 [SCHWERWIEGEND] java.lang.RuntimeException: Packet error (Version: v1_8_0, Class: null, Id: 0x20) -> null
02:57:39 [SCHWERWIEGEND]     at dev.wolveringer.bungeeutil.ExceptionUtils.createRuntimeException(ExceptionUtils.java:25)
02:57:39 [SCHWERWIEGEND]     at dev.wolveringer.bungeeutil.packets.creator.NormalPacketCreator.getPacket0(NormalPacketCreator.java:88)
02:57:39 [SCHWERWIEGEND]     at dev.wolveringer.bungeeutil.packets.creator.NormalPacketCreator.getPacket0(NormalPacketCreator.java:96)
02:57:39 [SCHWERWIEGEND]     at dev.wolveringer.bungeeutil.packets.creator.AbstractPacketCreator.getPacket(AbstractPacketCreator.java:49)
02:57:39 [SCHWERWIEGEND]     at dev.wolveringer.bungeeutil.packets.Packet.getPacket(Packet.java:158)
02:57:39 [SCHWERWIEGEND]     at dev.wolveringer.bungeeutil.netty.WarpedMinecraftDecoder.decode(WarpedMinecraftDecoder.java:97)
02:57:39 [SCHWERWIEGEND]     at dev.wolveringer.bungeeutil.netty.WarpedMinecraftDecoder.decode(WarpedMinecraftDecoder.java:31)
02:57:39 [SCHWERWIEGEND]     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
02:57:39 [SCHWERWIEGEND]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
02:57:39 [SCHWERWIEGEND]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
02:57:39 [SCHWERWIEGEND]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
02:57:39 [SCHWERWIEGEND]     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
02:57:39 [SCHWERWIEGEND]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
02:57:39 [SCHWERWIEGEND]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
02:57:39 [SCHWERWIEGEND]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
02:57:39 [SCHWERWIEGEND]     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
02:57:39 [SCHWERWIEGEND]     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
02:57:39 [SCHWERWIEGEND]     at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
02:57:39 [SCHWERWIEGEND]     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
02:57:39 [SCHWERWIEGEND]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
02:57:39 [SCHWERWIEGEND]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
02:57:39 [SCHWERWIEGEND]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
02:57:39 [SCHWERWIEGEND]     at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
02:57:39 [SCHWERWIEGEND]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
02:57:39 [SCHWERWIEGEND]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
02:57:39 [SCHWERWIEGEND]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
02:57:39 [SCHWERWIEGEND]     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
02:57:39 [SCHWERWIEGEND]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
02:57:39 [SCHWERWIEGEND]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
02:57:39 [SCHWERWIEGEND]     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
02:57:39 [SCHWERWIEGEND]     at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
02:57:39 [SCHWERWIEGEND]     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651)
02:57:39 [SCHWERWIEGEND]     at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574)
02:57:39 [SCHWERWIEGEND]     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488)
02:57:39 [SCHWERWIEGEND]     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)
02:57:39 [SCHWERWIEGEND]     at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
02:57:39 [SCHWERWIEGEND]     at java.lang.Thread.run(Thread.java:745)
02:57:39 [SCHWERWIEGEND] Caused by: java.lang.NullPointerException
02:57:39 [SCHWERWIEGEND]     at dev.wolveringer.bungeeutil.packets.PacketPlayOutEntityProperties.read(PacketPlayOutEntityProperties.java:69)
02:57:39 [SCHWERWIEGEND]     at dev.wolveringer.bungeeutil.packets.Packet.load(Packet.java:301)
02:57:39 [SCHWERWIEGEND]     at dev.wolveringer.bungeeutil.packets.creator.NormalPacketCreator.getPacket0(NormalPacketCreator.java:84)
02:57:39 [SCHWERWIEGEND]     ... 35 more
```

Changing the thing to check for null inside the read method fixes the error -> class is not properply initialized -> unsafe class allocation was used

Issue is gone with usage of parameter `-Dbungeeutil.no_unsave=1`

Also happens for other packets like PacketPlayOutStatistic:
```
03:00:47 [INFORMATION] An error happed. .RuntimeException message -> Packet error (Version: v1_8_0, Class: null, Id: 0x37) -> null
03:00:47 [SCHWERWIEGEND] java.lang.RuntimeException: Packet error (Version: v1_8_0, Class: null, Id: 0x37) -> null
03:00:47 [SCHWERWIEGEND]        at dev.wolveringer.bungeeutil.ExceptionUtils.createRuntimeException(ExceptionUtils.java:25)
03:00:47 [SCHWERWIEGEND]        at dev.wolveringer.bungeeutil.packets.creator.NormalPacketCreator.getPacket0(NormalPacketCreator.java:88)
03:00:47 [SCHWERWIEGEND]        at dev.wolveringer.bungeeutil.packets.creator.NormalPacketCreator.getPacket0(NormalPacketCreator.java:96)
03:00:47 [SCHWERWIEGEND]        at dev.wolveringer.bungeeutil.packets.creator.AbstractPacketCreator.getPacket(AbstractPacketCreator.java:49)
03:00:47 [SCHWERWIEGEND]        at dev.wolveringer.bungeeutil.packets.Packet.getPacket(Packet.java:158)
03:00:47 [SCHWERWIEGEND]        at dev.wolveringer.bungeeutil.netty.WarpedMinecraftDecoder.decode(WarpedMinecraftDecoder.java:97)
03:00:47 [SCHWERWIEGEND]        at dev.wolveringer.bungeeutil.netty.WarpedMinecraftDecoder.decode(WarpedMinecraftDecoder.java:31)
03:00:47 [SCHWERWIEGEND]        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
03:00:47 [SCHWERWIEGEND]        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
03:00:47 [SCHWERWIEGEND]        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
03:00:47 [SCHWERWIEGEND]        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
03:00:47 [SCHWERWIEGEND]        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
03:00:47 [SCHWERWIEGEND]        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
03:00:47 [SCHWERWIEGEND]        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
03:00:47 [SCHWERWIEGEND]        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
03:00:47 [SCHWERWIEGEND]        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
03:00:47 [SCHWERWIEGEND]        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
03:00:47 [SCHWERWIEGEND]        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
03:00:47 [SCHWERWIEGEND]        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
03:00:47 [SCHWERWIEGEND]        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
03:00:47 [SCHWERWIEGEND]        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
03:00:47 [SCHWERWIEGEND]        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
03:00:47 [SCHWERWIEGEND]        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
03:00:47 [SCHWERWIEGEND]        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
03:00:47 [SCHWERWIEGEND]        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
03:00:47 [SCHWERWIEGEND]        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
03:00:47 [SCHWERWIEGEND]        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
03:00:47 [SCHWERWIEGEND]        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
03:00:47 [SCHWERWIEGEND]        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
03:00:47 [SCHWERWIEGEND]        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
03:00:47 [SCHWERWIEGEND]        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
03:00:47 [SCHWERWIEGEND]        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651)
03:00:47 [SCHWERWIEGEND]        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574)
03:00:47 [SCHWERWIEGEND]        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488)
03:00:47 [SCHWERWIEGEND]        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)
03:00:47 [SCHWERWIEGEND]        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
03:00:47 [SCHWERWIEGEND]        at java.lang.Thread.run(Thread.java:745)
03:00:47 [SCHWERWIEGEND] Caused by: java.lang.NullPointerException
03:00:47 [SCHWERWIEGEND]        at dev.wolveringer.bungeeutil.packets.PacketPlayOutStatistic.read(PacketPlayOutStatistic.java:30)
03:00:47 [SCHWERWIEGEND]        at dev.wolveringer.bungeeutil.packets.Packet.load(Packet.java:301)
03:00:47 [SCHWERWIEGEND]        at dev.wolveringer.bungeeutil.packets.creator.NormalPacketCreator.getPacket0(NormalPacketCreator.java:84)
03:00:47 [SCHWERWIEGEND]        ... 35 more
```

**Comment by WolverinDEV** [comment]
Fixed.
This error coursed the new CachedPacketCreator witch sets the fields to null.
