### ISSUE TITLE
IndexOutOfBoundsException when a creeper explodes

### ISSUE THREAD

**Issue by Cornit** [WolverinDEV/BungeeUtil#46]
https://hastebin.com/siyowikamu.java

**Comment by Cornit** [comment]
https://hastebin.com/olehakazic.java meldung kommt wenn jemand joint

**Comment by kaerns** [comment]
Bei der join-meldung: hast du sicher alles kopiert? wenn ja dann hat das wahrscheinlich nichts mit bungeeutil zu tun. Ausserdem möchte ich dich bitten noch folgende Infos zur Verfügung zu stellen:
Bungeecord version (z.b. #1280)
Spigot server minecraft version (z.b. 1.8.9)
Client minecraft version (z.b. 1.12)
bungeeutil version (z.b. 2.5.3)
wenn viaversion installiert ist auch diese version und ob es auf bungeecord oder Spigot installiert wurde (z.b. 1.1.1 spigot)

**Comment by Cornit** [comment]
Ich bin mir sicher, dass ich alles kopiert habe ^^
Bungee: #1250
Spigot: 1.12
Client: 1.12
Bungeeutil: 2.5.4
Nein haben kein viaversion drauf

**Comment by WolverinDEV** [comment]
Hey,
der letzte Release von BungeeUtils functioniert nur mit dem letzten BungeeCord. Dein BungeeCord ist ein bissl veraltet :)
@essem2 Sorry das ich zurzeit gerade etwas inaktiv bin aber gerade eher stressing und habe keine wirkliche zeit BungeeUtils weiter zu führen. Aber sofern es geht fixe ich critical bugs

**Comment by Cornit** [comment]
das ist der neuste release gewesen xD
look: 
http://short.skydis.de/28a017

**Comment by kaerns** [comment]
konnte das problem nachstellen, wobei es anscheind keine sichtbaren probleme bis auf die zugespammte console verursacht.
BungeeUtil: 2.5.5
BungeeCord: 1258
Viaversion: 1.2
Client: 1.12
Server: 1.9.4

Keine Errors beim joinen von spielern oder start des servers, also nicht bungeeutil related.
Feststellungen: 
- Es passiert nur wenn blockschaden gemacht wird (gamerule mobGriefing = true)
- Es spielt keine rolle ob nur normale blöcke zerstört werden oder noch (tile)entities in der nähe sind.

Exception die ich rausbekommen hab: 
```
01:51:01 [INFO] An error happed. .IndexOutOfBoundsException message -> Packet error (Version: v1_9_3, Class: null, Id: 0x48) -> readerIndex(2) + length(109) exceeds writerIndex(3): UnpooledSlicedByteBuf(ridx: 2, widx: 3, cap: 3/3, unwrapped: PooledUnsafeDirectByteBuf(ridx: 28, widx: 28, cap: 96))
01:51:01 [SEVERE] java.lang.IndexOutOfBoundsException: Packet error (Version: v1_9_3, Class: null, Id: 0x48) -> readerIndex(2) + length(109) exceeds writerIndex(3): UnpooledSlicedByteBuf(ridx: 2, widx: 3, cap: 3/3, unwrapped: PooledUnsafeDirectByteBuf(ridx: 28, widx: 28, cap: 96))
01:51:01 [SEVERE] 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1396)
01:51:01 [SEVERE] 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1383)
01:51:01 [SEVERE] 	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:850)
01:51:01 [SEVERE] 	at dev.wolveringer.bungeeutil.packetlib.reader.PacketDataSerializer.readBytes(PacketDataSerializer.java:532)
01:51:01 [SEVERE] 	at dev.wolveringer.bungeeutil.packetlib.reader.PacketDataSerializer.readStringBytes(PacketDataSerializer.java:652)
01:51:01 [SEVERE] 	at dev.wolveringer.bungeeutil.packets.PacketPlayOutPlayerListHeaderFooter.read(PacketPlayOutPlayerListHeaderFooter.java:41)
01:51:01 [SEVERE] 	at dev.wolveringer.bungeeutil.packets.Packet.load(Packet.java:104)
01:51:01 [SEVERE] 	at dev.wolveringer.bungeeutil.packets.creator.NormalPacketCreator.getPacket0(NormalPacketCreator.java:90)
01:51:01 [SEVERE] 	at dev.wolveringer.bungeeutil.packets.creator.NormalPacketCreator.getPacket0(NormalPacketCreator.java:102)
01:51:01 [SEVERE] 	at dev.wolveringer.bungeeutil.packets.creator.CachedPacketCreator.getPacket0(CachedPacketCreator.java:134)
01:51:01 [SEVERE] 	at dev.wolveringer.bungeeutil.packets.creator.AbstractPacketCreator.getPacket(AbstractPacketCreator.java:51)
01:51:01 [SEVERE] 	at dev.wolveringer.bungeeutil.packetlib.PacketRegistry.getPacket(PacketRegistry.java:131)
01:51:01 [SEVERE] 	at dev.wolveringer.bungeeutil.netty.WarpedMinecraftDecoder.decode(WarpedMinecraftDecoder.java:98)
01:51:01 [SEVERE] 	at dev.wolveringer.bungeeutil.netty.WarpedMinecraftDecoder.decode(WarpedMinecraftDecoder.java:32)
01:51:01 [SEVERE] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
01:51:01 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
01:51:01 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
01:51:01 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
01:51:01 [SEVERE] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
01:51:01 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
01:51:01 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
01:51:01 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
01:51:01 [SEVERE] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
01:51:01 [SEVERE] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
01:51:01 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
01:51:01 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
01:51:01 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
01:51:01 [SEVERE] 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
01:51:01 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
01:51:01 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
01:51:01 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
01:51:01 [SEVERE] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
01:51:01 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
01:51:01 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
01:51:01 [SEVERE] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
01:51:01 [SEVERE] 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:979)
01:51:01 [SEVERE] 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:403)
01:51:01 [SEVERE] 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:306)
01:51:01 [SEVERE] 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
01:51:01 [SEVERE] 	at java.lang.Thread.run(Thread.java:745)
```
Mehr kann ich dir hier nicht unter die arme greifen @WolverinDEV

**Comment by WolverinDEV** [comment]
Fixed?

**Comment by kaerns** [comment]
nope just tested with the newest version.
But i got a hint while testhing:
it only happens when you pick up a dropped item, it has nothing todo with the explosion itself.

I'm sorry but this time i can't help. Did not found anything thats wrong and the stacktrace does also not really help (for me).
