### ISSUE TITLE
BungeeUtils fails to install on clean installation of BungeeCord

### ISSUE THREAD

**Issue by flori-schwa** [WolverinDEV/BungeeUtil#60]
OS: Windows 10
BungeeCord version: git:BungeeCord-Bootstrap:1.12-SNAPSHOT:e23195f:1299
BungeeUtil version: 2.6 (from Spigot download page)
No other plugins installed

Plugin load Log:

```17:51:43 [INFORMATION] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.12-SNAPSHOT:e23195f:1299 by SpigotMC
17:51:43 [INFORMATION] Loaded plugin cmd_find version git:cmd_find:1.12-SNAPSHOT:e23195f:1299 by SpigotMC
17:51:43 [INFORMATION] Loaded plugin BungeeUtil version 2.6 by WolverinDEV
17:51:43 [INFORMATION] Loaded plugin cmd_server version git:cmd_server:1.12-SNAPSHOT:e23195f:1299 by SpigotMC
17:51:43 [INFORMATION] Loaded plugin cmd_alert version git:cmd_alert:1.12-SNAPSHOT:e23195f:1299 by SpigotMC
17:51:43 [INFORMATION] Loaded plugin cmd_send version git:cmd_send:1.12-SNAPSHOT:e23195f:1299 by SpigotMC
17:51:43 [INFORMATION] Loaded plugin cmd_list version git:cmd_list:1.12-SNAPSHOT:e23195f:1299 by SpigotMC
17:51:43 [WARNUNG] Forced host server pvp is not defined
17:51:43 [INFORMATION] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.12-SNAPSHOT:e23195f:1299 by SpigotMC
17:51:43 [INFORMATION] Enabled plugin cmd_find version git:cmd_find:1.12-SNAPSHOT:e23195f:1299 by SpigotMC
17:51:43 [BungeeUntil] Detected Minecraft proxy type: BUNGEECORD
17:51:43 [BungeeUntil] Fetching update data.
17:51:44 [BungeeUntil] Injecting patches
17:51:44 [BungeeUntil] Starting BungeeUtil injection.
17:51:44 [BungeeUntil] Set modifiers for class UserConnection.class to "public"
17:51:44 [SCHWERWIEGEND] javassist.NotFoundException: net.md_5.bungee.UserConnection
17:51:44 [SCHWERWIEGEND]     at javassist.ClassPool.get(ClassPool.java:436)
17:51:44 [SCHWERWIEGEND]     at javassist.ClassPool.getCtClass(ClassPool.java:467)
17:51:44 [SCHWERWIEGEND]     at dev.wolveringer.bungeeutil.injector.InjectFiles.inject(InjectFiles.java:38)
17:51:44 [SCHWERWIEGEND]     at dev.wolveringer.bungeeutil.BungeeUtil.inject(BungeeUtil.java:121)
Loading BungeeUtil >> Injection BungeeUtils. Please wait.Loading BungeeUtil >> Injection BungeeUtils. Please wait.[[2K17:51:44 [SCHWERWIEGEND]     at dev.wolveringer.bungeeutil.plugin.Main.onEnable(Main.java:137)
17:51:44 [SCHWERWIEGEND]     at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
17:51:44 [SCHWERWIEGEND]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:268)
17:51:44 [SCHWERWIEGEND]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
17:51:44 [SCHWERWIEGEND]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
17:51:44 [BungeeUntil] A fatal error has blocked in the injection of BungeeUtil.
17:51:44 [BungeeUntil] Disable BungeeUtil
17:51:44 [INFORMATION] Enabled plugin BungeeUtil version 2.6 by WolverinDEV
17:51:44 [INFORMATION] Enabled plugin cmd_server version git:cmd_server:1.12-SNAPSHOT:e23195f:1299 by SpigotMC
17:51:44 [INFORMATION] Enabled plugin cmd_alert version git:cmd_alert:1.12-SNAPSHOT:e23195f:1299 by SpigotMC
17:51:44 [INFORMATION] Enabled plugin cmd_send version git:cmd_send:1.12-SNAPSHOT:e23195f:1299 by SpigotMC
17:51:44 [INFORMATION] Enabled plugin cmd_list version git:cmd_list:1.12-SNAPSHOT:e23195f:1299 by SpigotMC
17:51:45 [INFORMATION] Listening on /0.0.0.0:25565
```

**Comment by WolverinDEV** [comment]
Hey,
i'm really surprised about that. 
Does md_5 released a new bungeecord version?

**Comment by flori-schwa** [comment]
The bungeecord build is 10 days old: https://ci.md-5.net/job/BungeeCord/1299/

**Comment by WolverinDEV** [comment]
Hmm did you tried it with an oder build?

**Comment by flori-schwa** [comment]
Yes and surprisingly, the same thing occurred with those builds aswell
