### ISSUE TITLE
Error with Java 10

### ISSUE THREAD

**Issue by U-siro** [WolverinDEV/BungeeUtil#64]
12:04:57 [WARNING] Exception encountered when loading plugin: BungeeUtil
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
    at dev.wolveringer.bungeeutil.plugin.updater.UpdaterV2.updateTo(UpdaterV2.java:256)
    at dev.wolveringer.bungeeutil.plugin.updater.UpdaterV2.update(UpdaterV2.java:234)
    at dev.wolveringer.bungeeutil.plugin.Main.onEnable(Main.java:76)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:291)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:112)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
    at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
    ... 7 more

**Comment by WolverinDEV** [comment]
What the hell?
Java 11? Last time I tested it was Java 9 the newest.
Well seems sie a class within the standard library got removed
