### ISSUE TITLE
Funktioniert nicht

### ISSUE THREAD

**Issue by ghost** [WolverinDEV/BungeeUtil#69]
Ich habe folgende BungeeCord-Version: git:BungeeCord-Bootstrap:1.13-SNAPSHOT:715ec07:1344 by md_5

Mein BungeeCord stoppt immer direkt, nachdem ich BungeeCord starte. Anscheinend kann er ein Update nicht finden oder herunterladen. Ich nutze BungeeUtil-2.6.1. Anbei ist ein Ausschnitt des Logs:

```
[WARNUNG] Exception encountered when loading plugin: BungeeUtil
java.lang.NoClassDefFoundError: dev/wolveringer/configuration/Configuration
	at dev.wolveringer.bungeeutil.plugin.Main.onEnable(Main.java:48)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:281)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: dev.wolveringer.configuration.Configuration
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more
```

**Comment by kaerns** [comment]
BungeeUtil is currently not updated to 1.13+
duplicate to #66

**Comment by ghost** [comment]
Which bungeecord-version i have to use? @essemX 

Also you didn't saw the code, which i've posted. In the code, my bungee says, that he can't find the de.wolveringer.configuration,Configuration class

**Comment by kaerns** [comment]
the last supported version should be bungeecord#1329 (1.12.2) see #67 for a statement from the dev.
Also i saw your error log and its normal that it can't find some classes when its not built for 1.13+

**Comment by ghost** [comment]
Okay, thank you. But, i have a 1.8 network. Can i use the bungee 1.12.2 buil #1329 also? @essemX
And how do i implement BungeeUtil in my project using maven. I mean which dependency and repo?
