### ISSUE TITLE
Is not working

### ISSUE THREAD

**Issue by SteveTheEngineer** [WolverinDEV/BungeeUtil#72]
`[12:51:04 WARN]: Exception encountered when loading plugin: BungeeUtil
java.lang.NoSuchMethodError: net.md_5.bungee.BungeeCord.getConsoleReader()Ljline/console/ConsoleReader;
        at dev.wolveringer.bungeeutil.BungeeUtil.setPromt(BungeeUtil.java:333) ~[?:?]
        at dev.wolveringer.bungeeutil.BungeeUtil.setInformation(BungeeUtil.java:326) ~[?:?]
        at dev.wolveringer.bungeeutil.plugin.Main.onEnable(Main.java:50) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:261) [server.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:af2a23d:183]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:283) [server.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:af2a23d:183]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56) [server.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:af2a23d:183]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) [server.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:af2a23d:183]`

**Comment by kaerns** [comment]
duplicate to #61 
using BungeeCord instead of Waterfall is a hotfix

**Comment by SteveTheEngineer** [comment]
So will you fix it?

**Comment by kaerns** [comment]
The BungeeUtil Projects seems currently frozen so a fix is not scheduled.

hopefully someone will find some time and support this project by updating it.

**Comment by SteveTheEngineer** [comment]
Maybe I'll do it later
