### ISSUE TITLE
ProxiedPlayer can't be cast to Player

### ISSUE THREAD

**Issue by AsVaidas** [WolverinDEV/BungeeUtil#74]
```[21:44:07 WARN]: Error in dispatching command
java.lang.ClassCastException: net.md_5.bungee.UserConnection cannot be cast to dev.wolveringer.bungeeutil.player.Player
        at me.AsVaidas.ZCBans.Commands.unpunish.execute(unpunish.java:38) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:192) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:142) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:149) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:60) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:104) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:316) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:4936da5:312]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

My method: `unban((Player) BungeeCord.getInstance().getPlayer(s.getName()));`
Method signature: `private void unban(Player p)`

**Comment by oleonardosilva** [comment]
This error also occurs to me.

**Comment by WolverinDEV** [comment]
The project is not maintained anymore (Newer version on BungeeCord/Waterfall may raise some errors).
But if you want you could submit a fix :)
